// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class ApiSyncLog
{
    public int SyncLogId { get; set; }

    public string ApiName { get; set; }

    public string SyncType { get; set; }

    public int? RecordsFetched { get; set; }

    public int? RecordsInserted { get; set; }

    public int? RecordsUpdated { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string Status { get; set; }

    public string ErrorMessage { get; set; }
}