// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

/// <summary>
/// Stores Arabic language descriptions for parts (used for sticker printing)
/// </summary>
public partial class ArabicPartDescription
{
    /// <summary>
    /// Primary key
    /// </summary>
    public int ArabicDescriptionId { get; set; }

    /// <summary>
    /// Links to part via VwPart.PartNumber (ItemKey from SH2013)
    /// </summary>
    public string ItemKey { get; set; }

    /// <summary>
    /// Arabic description text
    /// </summary>
    public string ArabicDescription { get; set; }

    /// <summary>
    /// Soft delete flag
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Creation timestamp
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Last update timestamp
    /// </summary>
    public DateTime UpdatedAt { get; set; }

    /// <summary>
    /// User who created this record
    /// </summary>
    public string CreatedBy { get; set; }

    /// <summary>
    /// User who last updated this record
    /// </summary>
    public string UpdatedBy { get; set; }
}
