// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sh.Autofit.New.Entities.Models
{
    public partial class fn_GetCoupledModelsResult
    {
        public int? ConsolidatedModelId { get; set; }
    }
}
