// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class Manufacturer
{
    public int ManufacturerId { get; set; }

    public int ManufacturerCode { get; set; }

    public string ManufacturerName { get; set; }

    public string ManufacturerShortName { get; set; }

    public string CountryOfOrigin { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? LastSyncedAt { get; set; }

    public virtual ICollection<ConsolidatedVehicleModel> ConsolidatedVehicleModels { get; set; } = new List<ConsolidatedVehicleModel>();

    public virtual ICollection<VehicleRegistration> VehicleRegistrations { get; set; } = new List<VehicleRegistration>();

    public virtual ICollection<VehicleType> VehicleTypes { get; set; } = new List<VehicleType>();
}