// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class MappingStatistic
{
    public int StatId { get; set; }

    public DateOnly StatDate { get; set; }

    public int TotalMappings { get; set; }

    public int ActiveMappings { get; set; }

    public int MappingsCreatedToday { get; set; }

    public int MappingsUpdatedToday { get; set; }

    public int ManualMappings { get; set; }

    public int AigeneratedMappings { get; set; }

    public int ImportedMappings { get; set; }

    public int VehiclesWithMappings { get; set; }

    public int VehiclesWithoutMappings { get; set; }

    public int PartsWithMappings { get; set; }

    public int PartsWithoutMappings { get; set; }

    public int ActiveUsers { get; set; }

    public DateTime CreatedAt { get; set; }
}