// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class ModelCoupling
{
    public int ModelCouplingId { get; set; }

    public int ConsolidatedModelIdA { get; set; }

    public int ConsolidatedModelIdB { get; set; }

    public string CouplingType { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual ConsolidatedVehicleModel ConsolidatedModelIdANavigation { get; set; }

    public virtual ConsolidatedVehicleModel ConsolidatedModelIdBNavigation { get; set; }
}