// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class PartsMetadatum
{
    public int PartMetadataId { get; set; }

    public string ItemKey { get; set; }

    public string CompatibilityNotes { get; set; }

    public bool UniversalPart { get; set; }

    public string ImageUrl { get; set; }

    public string DatasheetUrl { get; set; }

    public string CustomDescription { get; set; }

    public bool UseCustomDescription { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}