// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class PartKitItem
{
    public int PartKitItemId { get; set; }

    public int PartKitId { get; set; }

    public string PartItemKey { get; set; }

    public int? DisplayOrder { get; set; }

    public string Notes { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual PartKit PartKit { get; set; }
}