// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class PendingVehicleReview
{
    public int PendingVehicleId { get; set; }

    public int ManufacturerCode { get; set; }

    public string ManufacturerName { get; set; }

    public int ModelCode { get; set; }

    public string ModelName { get; set; }

    public string CommercialName { get; set; }

    public int ManufacturingYear { get; set; }

    public int? EngineVolume { get; set; }

    public string FuelType { get; set; }

    public string TransmissionType { get; set; }

    public string TrimLevel { get; set; }

    public string FinishLevel { get; set; }

    public int? Horsepower { get; set; }

    public string DriveType { get; set; }

    public int? NumberOfDoors { get; set; }

    public int? NumberOfSeats { get; set; }

    public int? TotalWeight { get; set; }

    public decimal? SafetyRating { get; set; }

    public int? GreenIndex { get; set; }

    public string ReviewStatus { get; set; }

    public string ReviewedBy { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public string ReviewNotes { get; set; }

    public DateTime DiscoveredAt { get; set; }

    public string DiscoverySource { get; set; }

    public Guid? BatchId { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }
}
