// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class PopularSearch
{
    public int SearchId { get; set; }

    public string SearchType { get; set; }

    public string SearchTerm { get; set; }

    public int SearchCount { get; set; }

    public DateTime LastSearchedAt { get; set; }
}