// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sh.Autofit.New.Entities.Models;

public partial class ShAutofitContext : DbContext
{
    public ShAutofitContext(DbContextOptions<ShAutofitContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ApiSyncLog> ApiSyncLogs { get; set; }

    public virtual DbSet<Manufacturer> Manufacturers { get; set; }

    public virtual DbSet<MappingStatistic> MappingStatistics { get; set; }

    public virtual DbSet<PartKit> PartKits { get; set; }

    public virtual DbSet<PartKitItem> PartKitItems { get; set; }

    public virtual DbSet<PartsMetadatum> PartsMetadata { get; set; }

    public virtual DbSet<PopularSearch> PopularSearches { get; set; }

    public virtual DbSet<SystemSetting> SystemSettings { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserActivityLog> UserActivityLogs { get; set; }

    public virtual DbSet<VehiclePartsMapping> VehiclePartsMappings { get; set; }

    public virtual DbSet<VehiclePartsMappingsHistory> VehiclePartsMappingsHistories { get; set; }

    public virtual DbSet<VehicleRegistration> VehicleRegistrations { get; set; }

    public virtual DbSet<VehicleType> VehicleTypes { get; set; }

    public virtual DbSet<VwPart> VwParts { get; set; }

    // New entities for consolidated models and couplings
    public virtual DbSet<ConsolidatedVehicleModel> ConsolidatedVehicleModels { get; set; }

    public virtual DbSet<ModelCoupling> ModelCouplings { get; set; }

    public virtual DbSet<PartCoupling> PartCouplings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ApiSyncLog>(entity =>
        {
            entity.HasKey(e => e.SyncLogId).HasName("PK__ApiSyncL__A40EB308C5C323AC");

            entity.ToTable("ApiSyncLog");

            entity.HasIndex(e => e.ApiName, "IX_ApiSync_ApiName");

            entity.HasIndex(e => e.StartedAt, "IX_ApiSync_StartedAt");

            entity.HasIndex(e => e.Status, "IX_ApiSync_Status");

            entity.Property(e => e.ApiName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CompletedAt).HasPrecision(3);
            entity.Property(e => e.StartedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SyncType)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Manufacturer>(entity =>
        {
            entity.HasKey(e => e.ManufacturerId).HasName("PK__Manufact__357E5CC16CD08BB3");

            entity.HasIndex(e => e.ManufacturerCode, "IX_Manufacturers_Code");

            entity.HasIndex(e => e.ManufacturerName, "IX_Manufacturers_Name");

            entity.HasIndex(e => e.ManufacturerCode, "UQ__Manufact__DB6B63AC71E757A8").IsUnique();

            entity.Property(e => e.CountryOfOrigin).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Manufactu__Creat__4F7CD00D");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Manufactu__IsAct__4E88ABD4");
            entity.Property(e => e.LastSyncedAt).HasPrecision(3);
            entity.Property(e => e.ManufacturerName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ManufacturerShortName).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Manufactu__Updat__5070F446");
        });

        modelBuilder.Entity<MappingStatistic>(entity =>
        {
            entity.HasKey(e => e.StatId).HasName("PK__MappingS__3A162D3E0ABA2BFE");

            entity.HasIndex(e => e.StatDate, "IX_MappingStats_Date").IsDescending();

            entity.HasIndex(e => e.StatDate, "UQ_MappingStats_Date").IsUnique();

            entity.Property(e => e.AigeneratedMappings).HasColumnName("AIGeneratedMappings");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<PartsMetadatum>(entity =>
        {
            entity.HasKey(e => e.PartMetadataId).HasName("PK__PartsMet__09DFD27238F42E6F");

            entity.HasIndex(e => e.ItemKey, "IX_PartsMetadata_ItemKey");

            entity.HasIndex(e => e.UniversalPart, "IX_PartsMetadata_Universal");

            entity.HasIndex(e => e.ItemKey, "UQ__PartsMet__136EF542DCD43851").IsUnique();

            entity.Property(e => e.CompatibilityNotes).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CustomDescription).HasMaxLength(1000);
            entity.Property(e => e.DatasheetUrl).HasMaxLength(500);
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ItemKey)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
        });

        modelBuilder.Entity<PopularSearch>(entity =>
        {
            entity.HasKey(e => e.SearchId).HasName("PK__PopularS__21C535F4F31F0AD4");

            entity.HasIndex(e => new { e.SearchType, e.SearchCount }, "IX_PopularSearches_Type_Count").IsDescending(false, true);

            entity.HasIndex(e => new { e.SearchType, e.SearchTerm }, "UQ_PopularSearches").IsUnique();

            entity.Property(e => e.LastSearchedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.SearchCount).HasDefaultValue(1);
            entity.Property(e => e.SearchTerm)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.SearchType)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SystemSetting>(entity =>
        {
            entity.HasKey(e => e.SettingId).HasName("PK__SystemSe__54372B1DFBBBC0C7");

            entity.HasIndex(e => e.SettingKey, "IX_SystemSettings_Key");

            entity.HasIndex(e => e.SettingKey, "UQ__SystemSe__01E719ADDB39478A").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsEditable).HasDefaultValue(true);
            entity.Property(e => e.SettingKey)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C74B24397");

            entity.HasIndex(e => e.Username, "IX_Users_Username");

            entity.HasIndex(e => e.Username, "UQ__Users__536C85E42655BB81").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email).HasMaxLength(200);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastLoginAt).HasPrecision(3);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<UserActivityLog>(entity =>
        {
            entity.HasKey(e => e.ActivityId).HasName("PK__UserActi__45F4A791D4F98DAE");

            entity.ToTable("UserActivityLog");

            entity.HasIndex(e => e.CreatedAt, "IX_UserActivity_CreatedAt");

            entity.HasIndex(e => e.ActivityType, "IX_UserActivity_Type");

            entity.HasIndex(e => e.UserId, "IX_UserActivity_User");

            entity.Property(e => e.ActivityType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.EntityType).HasMaxLength(50);
            entity.Property(e => e.IpAddress).HasMaxLength(50);
            entity.Property(e => e.UserAgent).HasMaxLength(500);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.User).WithMany(p => p.UserActivityLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserActivity_User");
        });

        modelBuilder.Entity<VehiclePartsMapping>(entity =>
        {
            entity.HasKey(e => e.MappingId).HasName("PK__VehicleP__8B57819DACDD603B");

            entity.HasIndex(e => e.IsActive, "IX_VPMappings_Active");

            entity.HasIndex(e => e.IsCurrentVersion, "IX_VPMappings_CurrentVersion");

            entity.HasIndex(e => e.PartItemKey, "IX_VPMappings_PartItemKey");

            entity.HasIndex(e => e.MappingSource, "IX_VPMappings_Source");

            entity.HasIndex(e => e.VehicleTypeId, "IX_VPMappings_VehicleType");

            entity.HasIndex(e => new { e.VehicleTypeId, e.PartItemKey, e.IsCurrentVersion, e.IsActive }, "UQ_VehiclePartsMappings_Current").IsUnique();

            entity.Property(e => e.CompatibilityNotes).HasMaxLength(500);
            entity.Property(e => e.ConfidenceScore).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.DeactivatedAt).HasPrecision(3);
            entity.Property(e => e.DeactivatedBy).HasMaxLength(100);
            entity.Property(e => e.DeactivationReason).HasMaxLength(500);
            entity.Property(e => e.InstallationNotes).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsCurrentVersion).HasDefaultValue(true);
            entity.Property(e => e.MappingSource)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Manual");
            entity.Property(e => e.PartItemKey)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.VersionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.VehicleType).WithMany(p => p.VehiclePartsMappings)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VPMappings_VehicleType");
        });

        modelBuilder.Entity<VehiclePartsMappingsHistory>(entity =>
        {
            entity.HasKey(e => e.MappingHistoryId).HasName("PK__VehicleP__087EC28198BA3E06");

            entity.ToTable("VehiclePartsMappingsHistory");

            entity.HasIndex(e => e.ChangedAt, "IX_VPMappingsHistory_ChangedAt");

            entity.HasIndex(e => e.MappingId, "IX_VPMappingsHistory_Mapping");

            entity.HasIndex(e => e.PartItemKey, "IX_VPMappingsHistory_PartItemKey");

            entity.Property(e => e.ChangeReason).HasMaxLength(500);
            entity.Property(e => e.ChangeType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ChangedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ChangedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CompatibilityNotes).HasMaxLength(500);
            entity.Property(e => e.ConfidenceScore).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.InstallationNotes).HasMaxLength(1000);
            entity.Property(e => e.MappingSource)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PartItemKey)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Mapping).WithMany(p => p.VehiclePartsMappingsHistories)
                .HasForeignKey(d => d.MappingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VPMappingsHistory_Mapping");
        });

        modelBuilder.Entity<VehicleRegistration>(entity =>
        {
            entity.HasKey(e => e.RegistrationId).HasName("PK__VehicleR__6EF58810517590E5");

            entity.HasIndex(e => e.LicensePlate, "IX_VehicleReg_LicensePlate");

            entity.HasIndex(e => e.VehicleTypeId, "IX_VehicleReg_VehicleType");

            entity.HasIndex(e => e.LicensePlate, "UQ__VehicleR__026BC15CCA97FFFF").IsUnique();

            entity.Property(e => e.Color).HasMaxLength(50);
            entity.Property(e => e.CurrentOwner).HasMaxLength(200);
            entity.Property(e => e.FirstLookupDate)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastLookupDate)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LicensePlate)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LookupCount).HasDefaultValue(1);
            entity.Property(e => e.Vin)
                .HasMaxLength(50)
                .HasColumnName("VIN");

            entity.HasOne(d => d.Manufacturer).WithMany(p => p.VehicleRegistrations)
                .HasForeignKey(d => d.ManufacturerId)
                .HasConstraintName("FK_VehicleReg_Manufacturer");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.VehicleRegistrations)
                .HasForeignKey(d => d.VehicleTypeId)
                .HasConstraintName("FK_VehicleReg_VehicleType");
        });

        modelBuilder.Entity<VehicleType>(entity =>
        {
            entity.HasKey(e => e.VehicleTypeId).HasName("PK__VehicleT__9F449643E2144002");

            entity.HasIndex(e => e.VehicleCategory, "IX_VehicleTypes_Category");

            entity.HasIndex(e => e.CommercialName, "IX_VehicleTypes_CommercialName");

            entity.HasIndex(e => e.ManufacturerId, "IX_VehicleTypes_Manufacturer");

            entity.HasIndex(e => e.ModelCode, "IX_VehicleTypes_ModelCode");

            entity.HasIndex(e => e.YearFrom, "IX_VehicleTypes_YearFrom");

            entity.Property(e => e.CommercialName).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__VehicleTy__Creat__5441852A");
            entity.Property(e => e.EngineModel).HasMaxLength(100);
            entity.Property(e => e.FinishLevel).HasMaxLength(100);
            entity.Property(e => e.FrontTireSize).HasMaxLength(50);
            entity.Property(e => e.FuelTypeName).HasMaxLength(50);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__VehicleTy__IsAct__534D60F1");
            entity.Property(e => e.LastSyncedAt).HasPrecision(3);
            entity.Property(e => e.ModelCode).HasMaxLength(50);
            entity.Property(e => e.ModelName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.RearTireSize).HasMaxLength(50);
            entity.Property(e => e.SafetyRating).HasColumnType("money");
            entity.Property(e => e.TransmissionType).HasMaxLength(50);
            entity.Property(e => e.TrimLevel).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__VehicleTy__Updat__5535A963");
            entity.Property(e => e.VehicleCategory).HasMaxLength(100);

            entity.HasOne(d => d.Manufacturer).WithMany(p => p.VehicleTypes)
                .HasForeignKey(d => d.ManufacturerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VehicleTypes_Manufacturer");
        });

        modelBuilder.Entity<VwPart>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_Parts");

            entity.Property(e => e.BoxDimensions)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Category)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.CompatibilityNotes).HasMaxLength(500);
            entity.Property(e => e.CustomDescription).HasMaxLength(1000);
            entity.Property(e => e.DatasheetUrl).HasMaxLength(500);
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.Manufacturer)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.MetadataUpdatedAt).HasPrecision(3);
            entity.Property(e => e.Model)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Oemnumber1)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("OEMNumber1");
            entity.Property(e => e.Oemnumber2)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("OEMNumber2");
            entity.Property(e => e.Oemnumber3)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("OEMNumber3");
            entity.Property(e => e.Oemnumber4)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("OEMNumber4");
            entity.Property(e => e.Oemnumber5)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("OEMNumber5");
            entity.Property(e => e.PartName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PartNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PartKit>(entity =>
        {
            entity.HasKey(e => e.PartKitId);

            entity.ToTable("PartKit");

            entity.HasIndex(e => e.IsActive, "IX_PartKit_IsActive");

            entity.HasIndex(e => e.CreatedBy, "IX_PartKit_CreatedBy");

            entity.HasIndex(e => e.KitName, "UK_PartKit_KitName").IsUnique();

            entity.Property(e => e.KitName)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.Description)
                .HasMaxLength(1000);

            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValue(true);

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getutcdate())");

            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100);

            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3);
        });

        modelBuilder.Entity<PartKitItem>(entity =>
        {
            entity.HasKey(e => e.PartKitItemId);

            entity.ToTable("PartKitItem");

            entity.HasIndex(e => e.PartKitId, "IX_PartKitItem_PartKitId");

            entity.HasIndex(e => e.PartItemKey, "IX_PartKitItem_PartItemKey");

            entity.HasIndex(e => new { e.PartKitId, e.PartItemKey }, "UK_PartKitItem_Kit_Part").IsUnique();

            entity.Property(e => e.PartItemKey)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Notes)
                .HasMaxLength(500);

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.PartKit)
                .WithMany(p => p.PartKitItems)
                .HasForeignKey(d => d.PartKitId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PartKitItem_PartKit");
        });

        // =============================================
        // NEW ENTITY CONFIGURATIONS
        // =============================================

        modelBuilder.Entity<ConsolidatedVehicleModel>(entity =>
        {
            entity.HasKey(e => e.ConsolidatedModelId);

            entity.HasIndex(e => e.ManufacturerId, "IX_ConsolidatedModels_Manufacturer");
            entity.HasIndex(e => e.ManufacturerCode, "IX_ConsolidatedModels_ManufacturerCode");
            entity.HasIndex(e => e.ModelCode, "IX_ConsolidatedModels_ModelCode");
            entity.HasIndex(e => new { e.ManufacturerCode, e.ModelCode }, "IX_ConsolidatedModels_ManufacturerModel");
            entity.HasIndex(e => new { e.YearFrom, e.YearTo }, "IX_ConsolidatedModels_YearRange");
            entity.HasIndex(e => e.IsActive, "IX_ConsolidatedModels_Active");

            // Unique constraint on 7 fields that define a unique vehicle model
            entity.HasIndex(e => new
            {
                e.ManufacturerCode,
                e.ModelCode,
                e.ModelName,
                e.EngineVolume,
                e.TrimLevel,
                e.TransmissionType,
                e.FuelTypeCode
            }, "UQ_ConsolidatedModels_NaturalKey").IsUnique();

            entity.Property(e => e.ModelName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TrimLevel).HasMaxLength(100);
            entity.Property(e => e.FinishLevel).HasMaxLength(100);
            entity.Property(e => e.TransmissionType).HasMaxLength(50);
            entity.Property(e => e.FuelTypeName).HasMaxLength(50);
            entity.Property(e => e.CommercialName).HasMaxLength(100);
            entity.Property(e => e.EngineModel).HasMaxLength(100);
            entity.Property(e => e.VehicleCategory).HasMaxLength(100);
            entity.Property(e => e.SafetyRating).HasColumnType("decimal(3, 2)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValue("MIGRATION");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Manufacturer)
                .WithMany(p => p.ConsolidatedVehicleModels)
                .HasForeignKey(d => d.ManufacturerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ConsolidatedModels_Manufacturer");
        });

        modelBuilder.Entity<ModelCoupling>(entity =>
        {
            entity.HasKey(e => e.ModelCouplingId);

            entity.HasIndex(e => e.ConsolidatedModelId_A, "IX_ModelCouplings_ModelA");
            entity.HasIndex(e => e.ConsolidatedModelId_B, "IX_ModelCouplings_ModelB");
            entity.HasIndex(e => e.IsActive, "IX_ModelCouplings_Active");
            entity.HasIndex(e => new { e.ConsolidatedModelId_A, e.ConsolidatedModelId_B }, "UQ_ModelCouplings_Pair").IsUnique();

            entity.Property(e => e.CouplingType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("SameParts");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.ConsolidatedModelA)
                .WithMany(p => p.ModelCouplingsAsModelA)
                .HasForeignKey(d => d.ConsolidatedModelId_A)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ModelCouplings_ModelA");

            entity.HasOne(d => d.ConsolidatedModelB)
                .WithMany(p => p.ModelCouplingsAsModelB)
                .HasForeignKey(d => d.ConsolidatedModelId_B)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ModelCouplings_ModelB");
        });

        modelBuilder.Entity<PartCoupling>(entity =>
        {
            entity.HasKey(e => e.PartCouplingId);

            entity.HasIndex(e => e.PartItemKey_A, "IX_PartCouplings_PartA");
            entity.HasIndex(e => e.PartItemKey_B, "IX_PartCouplings_PartB");
            entity.HasIndex(e => e.IsActive, "IX_PartCouplings_Active");
            entity.HasIndex(e => new { e.PartItemKey_A, e.PartItemKey_B }, "UQ_PartCouplings_Pair").IsUnique();

            entity.Property(e => e.PartItemKey_A)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.PartItemKey_B)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CouplingType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Compatible");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        // Update VehicleType to include ConsolidatedModelId relationship
        modelBuilder.Entity<VehicleType>()
            .HasOne(d => d.ConsolidatedModel)
            .WithMany(p => p.VehicleTypes)
            .HasForeignKey(d => d.ConsolidatedModelId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_VehicleTypes_ConsolidatedModel");

        // Update VehiclePartsMapping configuration for new fields
        modelBuilder.Entity<VehiclePartsMapping>()
            .Property(e => e.VehicleTypeId)
            .IsRequired(false); // Now nullable

        modelBuilder.Entity<VehiclePartsMapping>()
            .Property(e => e.MappingLevel)
            .HasMaxLength(20)
            .HasDefaultValue("Legacy");

        modelBuilder.Entity<VehiclePartsMapping>()
            .HasOne(d => d.ConsolidatedModel)
            .WithMany(p => p.VehiclePartsMappings)
            .HasForeignKey(d => d.ConsolidatedModelId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_VPMappings_ConsolidatedModel");

        // Update Manufacturer to include ConsolidatedVehicleModels navigation
        modelBuilder.Entity<Manufacturer>()
            .HasMany(p => p.ConsolidatedVehicleModels)
            .WithOne(d => d.Manufacturer)
            .HasForeignKey(d => d.ManufacturerId);

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}