// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Sh.Autofit.New.Entities.Models;

namespace Sh.Autofit.New.Entities.Models
{
    public partial class ShAutofitContext
    {

        [DbFunction("fn_GetCoupledModels", "dbo")]
        public IQueryable<fn_GetCoupledModelsResult> fn_GetCoupledModels(int? ConsolidatedModelId)
        {
            return FromExpression(() => fn_GetCoupledModels(ConsolidatedModelId));
        }

        [DbFunction("fn_GetCoupledParts", "dbo")]
        public IQueryable<fn_GetCoupledPartsResult> fn_GetCoupledParts(string PartItemKey)
        {
            return FromExpression(() => fn_GetCoupledParts(PartItemKey));
        }

        [DbFunction("fn_GetPrimaryOEM", "dbo")]
        public static string fn_GetPrimaryOEM(string ItemKey)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fn_GetCoupledModelsResult>().HasNoKey();
            modelBuilder.Entity<fn_GetCoupledPartsResult>().HasNoKey();
        }
    }
}
