// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Sh.Autofit.New.Entities.Models;

namespace Sh.Autofit.New.Entities.Models
{
    public partial class ShAutofitContext
    {

        [DbFunction("fn_GetPrimaryOEM", "dbo")]
        public static string fn_GetPrimaryOEM(string ItemKey)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
