// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Sh.Autofit.New.Entities.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Sh.Autofit.New.Entities.Models
{
    public partial class ShAutofitContext
    {
        private IShAutofitContextProcedures _procedures;

        public virtual IShAutofitContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ShAutofitContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IShAutofitContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class ShAutofitContextProcedures : IShAutofitContextProcedures
    {
        private readonly ShAutofitContext _context;

        public ShAutofitContextProcedures(ShAutofitContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_BulkInsertMappingsResult>> sp_BulkInsertMappingsAsync(string mappings, string username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Mappings",
                    Size = -1,
                    Value = mappings ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Username",
                    Size = 200,
                    Value = username ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_BulkInsertMappingsResult>("EXEC @returnValue = [dbo].[sp_BulkInsertMappings] @Mappings = @Mappings, @Username = @Username", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_GetVehiclesForPartResult>> sp_GetVehiclesForPartAsync(string partItemKey, bool? includeInactive, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PartItemKey",
                    Size = 40,
                    Value = partItemKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IncludeInactive",
                    Value = includeInactive ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_GetVehiclesForPartResult>("EXEC @returnValue = [dbo].[sp_GetVehiclesForPart] @PartItemKey = @PartItemKey, @IncludeInactive = @IncludeInactive", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_UpsertMappingResult>> sp_UpsertMappingAsync(int? vehicleTypeId, string partItemKey, string mappingSource, decimal? confidenceScore, int? priority, int? fitsYearFrom, int? fitsYearTo, bool? requiresModification, string compatibilityNotes, string installationNotes, string username, string changeReason, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "VehicleTypeId",
                    Value = vehicleTypeId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PartItemKey",
                    Size = 40,
                    Value = partItemKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MappingSource",
                    Size = 100,
                    Value = mappingSource ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ConfidenceScore",
                    Precision = 5,
                    Scale = 2,
                    Value = confidenceScore ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Priority",
                    Value = priority ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FitsYearFrom",
                    Value = fitsYearFrom ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FitsYearTo",
                    Value = fitsYearTo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "RequiresModification",
                    Value = requiresModification ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "CompatibilityNotes",
                    Size = 1000,
                    Value = compatibilityNotes ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "InstallationNotes",
                    Size = 2000,
                    Value = installationNotes ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Username",
                    Size = 200,
                    Value = username ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ChangeReason",
                    Size = 1000,
                    Value = changeReason ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_UpsertMappingResult>("EXEC @returnValue = [dbo].[sp_UpsertMapping] @VehicleTypeId = @VehicleTypeId, @PartItemKey = @PartItemKey, @MappingSource = @MappingSource, @ConfidenceScore = @ConfidenceScore, @Priority = @Priority, @FitsYearFrom = @FitsYearFrom, @FitsYearTo = @FitsYearTo, @RequiresModification = @RequiresModification, @CompatibilityNotes = @CompatibilityNotes, @InstallationNotes = @InstallationNotes, @Username = @Username, @ChangeReason = @ChangeReason", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
