// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sh.Autofit.New.Entities.Models
{
    public partial class sp_GetConsolidatedModelsForLookupResult
    {
        public int ConsolidatedModelId { get; set; }
        public int ManufacturerId { get; set; }
        public int ManufacturerCode { get; set; }
        public int ModelCode { get; set; }
        [StringLength(200)]
        public string ModelName { get; set; }
        public int? EngineVolume { get; set; }
        [StringLength(100)]
        public string TrimLevel { get; set; }
        [StringLength(50)]
        public string TransmissionType { get; set; }
        public int? FuelTypeCode { get; set; }
        [StringLength(50)]
        public string FuelTypeName { get; set; }
        public int YearFrom { get; set; }
        public int? YearTo { get; set; }
        [StringLength(100)]
        public string FinishLevel { get; set; }
        public int? NumberOfDoors { get; set; }
        public int? Horsepower { get; set; }
        [StringLength(100)]
        public string CommercialName { get; set; }
        [StringLength(100)]
        public string EngineModel { get; set; }
        [StringLength(100)]
        public string VehicleCategory { get; set; }
        public int? EmissionGroup { get; set; }
        public int? GreenIndex { get; set; }
        [Column("SafetyRating", TypeName = "decimal(10,2)")]
        public decimal? SafetyRating { get; set; }
        public int? SafetyLevel { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        [StringLength(100)]
        public string UpdatedBy { get; set; }
        [StringLength(50)]
        public string DriveType { get; set; }
        public int? NumberOfSeats { get; set; }
        [StringLength(50)]
        public string WeightRange { get; set; }
        [StringLength(200)]
        public string ManufacturerName { get; set; }
        [StringLength(100)]
        public string CountryOfOrigin { get; set; }
        public int? MappingCount { get; set; }
    }
}
