// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sh.Autofit.New.Entities.Models
{
    public partial class sp_GetVehiclesForPartResult
    {
        public int MappingId { get; set; }
        public int VehicleTypeId { get; set; }
        public int ManufacturerId { get; set; }
        [StringLength(50)]
        public string ModelCode { get; set; }
        [StringLength(200)]
        public string ModelName { get; set; }
        [StringLength(100)]
        public string CommercialName { get; set; }
        [StringLength(100)]
        public string FinishLevel { get; set; }
        public int YearFrom { get; set; }
        public int? YearTo { get; set; }
        public int? EngineVolume { get; set; }
        public int? TotalWeight { get; set; }
        [StringLength(100)]
        public string EngineModel { get; set; }
        public int? FuelTypeCode { get; set; }
        [StringLength(50)]
        public string FuelTypeName { get; set; }
        [StringLength(50)]
        public string TransmissionType { get; set; }
        public int? NumberOfDoors { get; set; }
        public int? NumberOfSeats { get; set; }
        public int? Horsepower { get; set; }
        [StringLength(100)]
        public string TrimLevel { get; set; }
        [StringLength(100)]
        public string VehicleCategory { get; set; }
        public int? EmissionGroup { get; set; }
        public int? GreenIndex { get; set; }
        [Column("SafetyRating", TypeName = "money")]
        public decimal? SafetyRating { get; set; }
        public int? SafetyLevel { get; set; }
        [StringLength(50)]
        public string FrontTireSize { get; set; }
        [StringLength(50)]
        public string RearTireSize { get; set; }
        [StringLength(2147483647)]
        public string AdditionalSpecs { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public DateTime? LastSyncedAt { get; set; }
        public int? ConsolidatedModelId { get; set; }
        [StringLength(50)]
        public string DriveType { get; set; }
        [StringLength(50)]
        public string GovernmentModelCode { get; set; }
        public int? GovernmentManufacturerCode { get; set; }
        public DateTime? LastSyncedFromGov { get; set; }
        [StringLength(200)]
        public string ManufacturerName { get; set; }
        public int Priority { get; set; }
        public int? FitsYearFrom { get; set; }
        public int? FitsYearTo { get; set; }
        public bool RequiresModification { get; set; }
        [StringLength(500)]
        public string CompatibilityNotes { get; set; }
        [StringLength(50)]
        public string MappingSource { get; set; }
        public DateTime MappingUpdatedAt { get; set; }
    }
}
