// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class UserActivityLog
{
    public int ActivityId { get; set; }

    public int? UserId { get; set; }

    public string Username { get; set; }

    public string ActivityType { get; set; }

    public string EntityType { get; set; }

    public int? EntityId { get; set; }

    public string Description { get; set; }

    public string IpAddress { get; set; }

    public string UserAgent { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}