// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class VehicleRegistration
{
    public int RegistrationId { get; set; }

    public string LicensePlate { get; set; }

    public int? VehicleTypeId { get; set; }

    public int? ManufacturerId { get; set; }

    public int? RegistrationYear { get; set; }

    public string Color { get; set; }

    public string CurrentOwner { get; set; }

    public string Vin { get; set; }

    public DateTime FirstLookupDate { get; set; }

    public DateTime LastLookupDate { get; set; }

    public int LookupCount { get; set; }

    public bool IsActive { get; set; }

    public string GovManufacturerName { get; set; }

    public string GovModelName { get; set; }

    public int? GovEngineVolume { get; set; }

    public string GovFuelType { get; set; }

    public int? GovYear { get; set; }

    public string MatchStatus { get; set; }

    public string MatchReason { get; set; }

    public string ApiResourceUsed { get; set; }

    public string ApiResponseJson { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }

    public virtual VehicleType VehicleType { get; set; }
}