// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class VehiclePartsMappingsHistory
{
    public int MappingHistoryId { get; set; }

    public int MappingId { get; set; }

    public int VehicleTypeId { get; set; }

    public string PartItemKey { get; set; }

    public string MappingSource { get; set; }

    public decimal? ConfidenceScore { get; set; }

    public int Priority { get; set; }

    public int? FitsYearFrom { get; set; }

    public int? FitsYearTo { get; set; }

    public bool RequiresModification { get; set; }

    public string CompatibilityNotes { get; set; }

    public string InstallationNotes { get; set; }

    public int VersionNumber { get; set; }

    public string ChangeType { get; set; }

    public string ChangeReason { get; set; }

    public DateTime ChangedAt { get; set; }

    public string ChangedBy { get; set; }

    public virtual VehiclePartsMapping Mapping { get; set; }
}