// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class VehicleType
{
    public int VehicleTypeId { get; set; }

    public int ManufacturerId { get; set; }

    public string ModelCode { get; set; }

    public string ModelName { get; set; }

    public string CommercialName { get; set; }

    public string FinishLevel { get; set; }

    public int YearFrom { get; set; }

    public int? YearTo { get; set; }

    public int? EngineVolume { get; set; }

    public int? TotalWeight { get; set; }

    public string EngineModel { get; set; }

    public int? FuelTypeCode { get; set; }

    public string FuelTypeName { get; set; }

    public string TransmissionType { get; set; }

    public int? NumberOfDoors { get; set; }

    public int? NumberOfSeats { get; set; }

    public int? Horsepower { get; set; }

    public string TrimLevel { get; set; }

    public string VehicleCategory { get; set; }

    public int? EmissionGroup { get; set; }

    public int? GreenIndex { get; set; }

    public decimal? SafetyRating { get; set; }

    public int? SafetyLevel { get; set; }

    public string FrontTireSize { get; set; }

    public string RearTireSize { get; set; }

    public string AdditionalSpecs { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? LastSyncedAt { get; set; }

    // Link to consolidated model (for audit trail and migration tracking)
    public int? ConsolidatedModelId { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }

    public virtual ConsolidatedVehicleModel ConsolidatedModel { get; set; }

    public virtual ICollection<VehiclePartsMapping> VehiclePartsMappings { get; set; } = new List<VehiclePartsMapping>();

    public virtual ICollection<VehicleRegistration> VehicleRegistrations { get; set; } = new List<VehicleRegistration>();
}