// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class VehiclePartsMapping
{
    public int MappingId { get; set; }

    // Legacy mapping (to individual VehicleType) - Now nullable
    public int? VehicleTypeId { get; set; }

    // New consolidated mapping (to ConsolidatedVehicleModel)
    public int? ConsolidatedModelId { get; set; }

    public string PartItemKey { get; set; }

    public string MappingSource { get; set; }

    public decimal? ConfidenceScore { get; set; }

    public int Priority { get; set; }

    public int? FitsYearFrom { get; set; }

    public int? FitsYearTo { get; set; }

    public bool RequiresModification { get; set; }

    public string CompatibilityNotes { get; set; }

    public string InstallationNotes { get; set; }

    public int VersionNumber { get; set; }

    public bool IsCurrentVersion { get; set; }

    // Mapping Level: 'Legacy' (VehicleTypeId-based) or 'Consolidated' (ConsolidatedModelId-based)
    public string MappingLevel { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsActive { get; set; }

    public DateTime? DeactivatedAt { get; set; }

    public string DeactivatedBy { get; set; }

    public string DeactivationReason { get; set; }

    // Navigation Properties
    public virtual ICollection<VehiclePartsMappingsHistory> VehiclePartsMappingsHistories { get; set; } = new List<VehiclePartsMappingsHistory>();

    public virtual VehicleType VehicleType { get; set; }

    public virtual ConsolidatedVehicleModel ConsolidatedModel { get; set; }
}