// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class VirtualPart
{
    public int VirtualPartId { get; set; }

    public string PartNumber { get; set; }

    public string PartName { get; set; }

    public string OemNumber1 { get; set; }

    public string OemNumber2 { get; set; }

    public string OemNumber3 { get; set; }

    public string OemNumber4 { get; set; }

    public string OemNumber5 { get; set; }

    public string Category { get; set; }

    public string Notes { get; set; }

    public int? CreatedForVehicleTypeId { get; set; }

    public int? CreatedForConsolidatedModelId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual VehicleType CreatedForVehicleType { get; set; }

    public virtual ConsolidatedVehicleModel CreatedForConsolidatedModel { get; set; }
}
