// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class VirtualPartMigrationLog
{
    public int MigrationId { get; set; }

    public string VirtualPartNumber { get; set; }

    public string RealPartNumber { get; set; }

    public string MatchedOemNumbers { get; set; }

    public int MappingsTransferred { get; set; }

    public string MigratedBy { get; set; }

    public DateTime MigratedAt { get; set; }

    public string VirtualPartData { get; set; }
}
