// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sh.Autofit.New.Entities.Models;

public partial class VwPart
{
    public string PartNumber { get; set; }

    public string PartName { get; set; }

    public double? RetailPrice { get; set; }

    public double? CostPrice { get; set; }

    public double? StockQuantity { get; set; }

    public string Oemnumber1 { get; set; }

    public string Oemnumber2 { get; set; }

    public string Oemnumber3 { get; set; }

    public string Oemnumber4 { get; set; }

    public string Oemnumber5 { get; set; }

    public string Manufacturer { get; set; }

    public string Model { get; set; }

    public string Category { get; set; }

    public string BoxDimensions { get; set; }

    public int IsInStock { get; set; }

    public int IsActive { get; set; }

    public string CompatibilityNotes { get; set; }

    public bool UniversalPart { get; set; }

    public string ImageUrl { get; set; }

    public string DatasheetUrl { get; set; }

    public string CustomDescription { get; set; }

    public bool UseCustomDescription { get; set; }

    public DateTime? MetadataUpdatedAt { get; set; }

    public string ArabicDescription { get; set; }
}